//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucaniss.Tools.DynamicProxy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucaniss.Tools.DynamicProxy.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor handler instance is null..
        /// </summary>
        internal static string InterceptorHandlerInstanceIsNull {
            get {
                return ResourceManager.GetString("InterceptorHandlerInstanceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor instance is null..
        /// </summary>
        internal static string InterceptorInstanceIsNull {
            get {
                return ResourceManager.GetString("InterceptorInstanceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interceptor is null..
        /// </summary>
        internal static string InterceptorNullReference {
            get {
                return ResourceManager.GetString("InterceptorNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orginal instance and interceptor types are not compatible..
        /// </summary>
        internal static string OriginalInstanceAndInterceptorTypesAreNotCompatible {
            get {
                return ResourceManager.GetString("OriginalInstanceAndInterceptorTypesAreNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orignal instance is null..
        /// </summary>
        internal static string OriginalInstanceIsNull {
            get {
                return ResourceManager.GetString("OriginalInstanceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public methods have to be virtual..
        /// </summary>
        internal static string OriginalInstancePublicMethodsMustBeVirtual {
            get {
                return ResourceManager.GetString("OriginalInstancePublicMethodsMustBeVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy method &apos;{0}&apos; not found..
        /// </summary>
        internal static string ProxyMethodNotFound {
            get {
                return ResourceManager.GetString("ProxyMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy method &apos;{0}&apos; was not invoked..
        /// </summary>
        internal static string ProxyMethodNotInvoked {
            get {
                return ResourceManager.GetString("ProxyMethodNotInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxu method &apos;{0}&apos; was already invoked..
        /// </summary>
        internal static string ProxyMethodWasInvoked {
            get {
                return ResourceManager.GetString("ProxyMethodWasInvoked", resourceCulture);
            }
        }
    }
}
